- name: Just a Demo Play
  hosts: localhost
  vars:
    url: play.example.com
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ url }}

- name: Just a Demo Play - on a task level instead
  hosts: localhost
  #vars:
  #  url: play.example.com
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ url1 }}
      vars:
        url1: task.example.com

- name: play level but taking vars from an external file
  hosts: localhost
  vars_files:
    - sample-vars.yml
  #vars:
  #  url: play.example.com
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ url2 }}
      vars:
        url1: task.example.com

- name: gather facts from ansible
  hosts: localhost
  vars_files:
    - sample-vars.yml
  #vars:
  #  url: play.example.com
  tasks:
    - name: Print a Fact
      ansible.builtin.debug:
        msg: Hostname = {{ ansible_hostname }}

- name: Defining a variable in runtime using set_facts
  hosts: localhost
  tasks:
    - name: execute uptime shell command
      ansible.builtin.shell: uptime
      register: out

    -name: Print out
     ansible.builtin.debug:
      msg: "{{ out }}"
      