- name: Just a Demo Play
  hosts: localhost
  vars:
    url: play.example.com
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ url }}

- name: Just a Demo Play - on a task level instead
  hosts: localhost
  #vars:
  #  url: play.example.com
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ url1 }}
      vars:
        url1: task.example.com

- name: play level but taking vars from an external file
  hosts: localhost
  vars_files:
    - sample-vars.yml
  #vars:
  #  url: play.example.com
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ url2 }}
      vars:
        url1: task.example.com

- name: play level but taking vars from an inventory file
  hosts: localhost
  vars_files:
    - sample-vars.yml
  #vars:
  #  url: play.example.com
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ url3 }}
      vars:
        url1: task.example.com