- name: Just a Demo Play
  hosts: localhost
  vars:
    url: play.example.com
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ url }}

- name: Just a Demo Play - on a task level instead
  hosts: localhost
  #vars:
  #  url: play.example.com
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ url1 }}
      vars:
        url1: task.example.com